// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System.IO;
using System.Reflection;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CodeFormat.Rules
{
    /// <summary>
    ///  Ensure the file starts with the correct copyright comment.
    /// </summary>
    public class CopyrightCommentRule : CSharpSyntaxRewriter
    {
        public string CommentText;
        public SyntaxTriviaList Comment;

        public CopyrightCommentRule()
        {
            string copyrightCommentFilePath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "CopyrightComment.txt");
            CommentText = File.ReadAllText(copyrightCommentFilePath).TrimEnd() + "\r\n\r\n";
            Comment = CSharpSyntaxTree.ParseText(CommentText).GetRoot().GetLeadingTrivia();
        }

        public override SyntaxNode VisitCompilationUnit(CompilationUnitSyntax node)
        {
            string leadingComment = node.GetLeadingTrivia().ToFullString();
            if (leadingComment.StartsWith(CommentText) || leadingComment.Contains("<auto-generated>"))
            {
                return node;
            }
            else
            {
                return node.WithLeadingTrivia(Comment);
            }
        }
    }
}